export type AccentModel = 'us' | 'uk'

export type WorkplacePhrase = {
  phrase: string
  use: string
}

export type EnglishPracticeDay = {
  day: number
  week: string
  title: string
  focus: string
  listeningFocus: string
  mechanicsTitle: string
  mechanicsCue: string
  drillWords: string[]
  shadowCue: string
  speakingPrompt: string
  workplace: WorkplacePhrase[]
}

export const practiceResources = {
  bbc: {
    label: 'BBC Learning English',
    url: 'https://feeds.bbci.co.uk/learningenglish',
    detail: 'UK model · short programmes with transcripts',
  },
  voa: {
    label: 'VOA Learning English',
    url: 'https://learningenglish.voanews.com/',
    detail: 'US model · clear, controlled-speed news and lessons',
  },
  minimalPairs: {
    label: 'EnglishClub minimal pairs',
    url: 'https://www.englishclub.com/pronunciation/minimal-pairs.php',
    detail: 'Free contrast lists with audio',
  },
  cambridge: {
    label: 'Cambridge pronunciation',
    url: 'https://dictionary.cambridge.org/us/pronunciation/',
    detail: 'UK and US dictionary audio with IPA',
  },
  youglish: {
    label: 'YouGlish',
    url: 'https://youglish.com/',
    detail: 'Real-world examples across US, UK, and other accents',
  },
  bbcSchwa: {
    label: 'BBC schwa workshop',
    url: 'https://downloads.bbc.co.uk/learningenglish/towardsadvanced/unit_6/bbc_tims_pron_wkshp_schwa.pdf',
    detail: 'Transcript and exercises for the most common weak vowel',
  },
} as const

export const englishPracticeDays: EnglishPracticeDay[] = [
  {
    day: 1,
    week: 'Foundation',
    title: 'Baseline and one accent model',
    focus: 'Measure clarity without trying to erase your accent.',
    listeningFocus: 'Choose one clear 1–2 minute clip you understand at least 70%. Listen for melody and pauses before reading its transcript.',
    mechanicsTitle: 'Baseline contrast · /ɪ/ vs /iː/',
    mechanicsCue: 'Listen first, then say each pair slowly. Keep /iː/ longer with spread lips; keep /ɪ/ shorter and relaxed.',
    drillWords: ['ship / sheep', 'live / leave', 'sit / seat', 'fill / feel'],
    shadowCue: 'Record one untouched baseline, then shadow only the first two sentences at 0.75×. Do not chase speed today.',
    speakingPrompt: 'Introduce yourself, your role, and the English situation you most want to handle clearly. Speak for 60 seconds.',
    workplace: [
      { phrase: 'Let me give you a quick update on my progress.', use: 'Open a status update.' },
      { phrase: 'I have completed the first part, and I am working on the next step.', use: 'Report completed and current work.' },
      { phrase: 'Please let me know if you would like more detail.', use: 'Invite questions politely.' },
    ],
  },
  {
    day: 2,
    week: 'Foundation',
    title: 'Hear the vowel before producing it',
    focus: 'Strengthen /ɪ/ and /iː/ discrimination.',
    listeningFocus: 'Replay yesterday’s clip without text. Dictate two sentences, then compare every vowel with the transcript.',
    mechanicsTitle: 'Minimal pair · short /ɪ/ and long /iː/',
    mechanicsCue: 'Randomise the pairs. Point to the word you hear, then produce both. Check four words in Cambridge audio.',
    drillWords: ['bit / beat', 'slip / sleep', 'pick / peak', 'chip / cheap'],
    shadowCue: 'Shadow the same clip with text at a one-second lag. Mark the stressed syllable in every important word.',
    speakingPrompt: 'Explain what you worked on yesterday and what you will do today in 60–90 seconds.',
    workplace: [
      { phrase: 'Could you clarify what you mean by the final requirement?', use: 'Ask for a precise explanation.' },
      { phrase: 'If I understood correctly, the deadline is Friday.', use: 'Confirm your understanding.' },
      { phrase: 'Would you mind giving me an example?', use: 'Request an example politely.' },
    ],
  },
  {
    day: 3,
    week: 'Foundation',
    title: 'Open vowels and jaw movement',
    focus: 'Separate /æ/, /e/, and /ʌ/ with visible mouth movement.',
    listeningFocus: 'Listen to the same clip at normal speed, then 0.75×. Note three words whose vowel changed in your first dictation.',
    mechanicsTitle: 'Vowel triangle · /æ/ /e/ /ʌ/',
    mechanicsCue: 'Use a mirror: jaw drops most for /æ/, less for /e/, and stays relaxed for /ʌ/. Keep the word to one beat.',
    drillWords: ['bad / bed', 'bat / bet', 'bat / but', 'cap / cup'],
    shadowCue: 'Shadow sentence by sentence with text. Exaggerate stressed vowels once, then repeat naturally.',
    speakingPrompt: 'Describe one technical problem you solved recently: context, action, and result.',
    workplace: [
      { phrase: 'I see your point, but I have a different concern.', use: 'Disagree without sounding dismissive.' },
      { phrase: 'From my perspective, the simpler option is less risky.', use: 'State a professional opinion.' },
      { phrase: 'Could we compare both approaches before deciding?', use: 'Move disagreement toward evidence.' },
    ],
  },
  {
    day: 4,
    week: 'Foundation',
    title: 'Voicing control',
    focus: 'Feel the difference between /f/ and /v/.',
    listeningFocus: 'Listen once without text and tally every pause. Listen again and check whether the speaker pauses between ideas, not after every word.',
    mechanicsTitle: 'Minimal pair · /f/ vs /v/',
    mechanicsCue: 'Touch your throat. /v/ vibrates; /f/ does not. Keep the lower lip lightly against the upper teeth.',
    drillWords: ['fan / van', 'fine / vine', 'safe / save', 'leaf / leave'],
    shadowCue: 'Shadow yesterday’s sentences without text. Keep going after mistakes and recover at the next pause.',
    speakingPrompt: 'Schedule a 20-minute meeting and explain why it is needed.',
    workplace: [
      { phrase: 'Are you available for a short discussion tomorrow afternoon?', use: 'Request a meeting.' },
      { phrase: 'I would like to align on the next steps before we proceed.', use: 'Explain the meeting purpose.' },
      { phrase: 'If that time does not work, please suggest an alternative.', use: 'Offer scheduling flexibility.' },
    ],
  },
  {
    day: 5,
    week: 'Foundation',
    title: 'The two “th” sounds',
    focus: 'Place the tongue visibly between the teeth for /θ/ and /ð/.',
    listeningFocus: 'Final pass on this five-day clip: dictate the full first 30 seconds, compare with text, and list only two recurring misses.',
    mechanicsTitle: 'Tongue placement · /θ/ /ð/ vs /s/ /d/',
    mechanicsCue: 'Let air pass over the tongue for thin; add voice for this. Do not replace the sound with t, d, or s.',
    drillWords: ['thin / sin', 'free / three', 'then / den', 'they / day'],
    shadowCue: 'Full-speed overlap shadowing for the chosen section. Record the last pass and compare only stress and “th”.',
    speakingPrompt: 'Report one blocker, its impact, and the help you need.',
    workplace: [
      { phrase: 'I am currently blocked by an issue with the test environment.', use: 'Name a blocker directly.' },
      { phrase: 'This may affect the delivery date if it is not resolved today.', use: 'Explain impact without drama.' },
      { phrase: 'Could someone from the platform team help me investigate it?', use: 'Request specific help.' },
    ],
  },
  {
    day: 6,
    week: 'Foundation',
    title: 'Separate /r/ and /l/',
    focus: 'Use different tongue positions rather than guessing from spelling.',
    listeningFocus: 'Choose the next 1–2 minute clip in the same accent model. Listen twice silently and mark its thought groups with slashes.',
    mechanicsTitle: 'Tongue placement · /r/ vs /l/',
    mechanicsCue: 'For /r/, pull the tongue back without touching the roof. For /l/, touch the ridge behind the upper teeth.',
    drillWords: ['rice / lice', 'right / light', 'correct / collect', 'road / load'],
    shadowCue: 'Slow shadow the new clip at 0.75× with text. Copy the pause pattern before copying speed.',
    speakingPrompt: 'Estimate a small task and explain what could change the estimate.',
    workplace: [
      { phrase: 'My current estimate is two working days.', use: 'Give a clear estimate.' },
      { phrase: 'That estimate assumes the API remains unchanged.', use: 'State an assumption.' },
      { phrase: 'I will update you if I find any additional complexity.', use: 'Set an expectation for changes.' },
    ],
  },
  {
    day: 7,
    week: 'Foundation',
    title: 'Week-one clarity check',
    focus: 'Compare recordings, not feelings.',
    listeningFocus: 'Replay the new clip and write one sentence from dictation. Count content-word misses separately from small grammar-word misses.',
    mechanicsTitle: 'Review the three weakest contrasts',
    mechanicsCue: 'Use your recordings to choose only three pairs. Listen, identify, produce, record, and verify with dictionary audio.',
    drillWords: ['ship / sheep', 'fan / van', 'thin / sin', 'rice / lice'],
    shadowCue: 'Repeat the same 30-second section three times: with text, without text, then full-speed overlap. Save the final recording.',
    speakingPrompt: 'Record the same self-introduction from Day 1. Compare pauses, stress, and ASR transcription—not accent strength.',
    workplace: [
      { phrase: 'To summarise, we agreed on three next steps.', use: 'Close a discussion.' },
      { phrase: 'I will send the notes and action items after this call.', use: 'Take ownership of follow-up.' },
      { phrase: 'Please correct me if I missed anything important.', use: 'Invite corrections.' },
    ],
  },
  {
    day: 8,
    week: 'Sound clean-up',
    title: 'Schwa: the relaxed vowel',
    focus: 'Reduce unstressed vowels instead of pronouncing every letter equally.',
    listeningFocus: 'Listen for weak syllables in your clip. Underline the strong vowel and cross out spelling that disappears in speech.',
    mechanicsTitle: 'Reduction · /ə/',
    mechanicsCue: 'Relax jaw and tongue. Say the unstressed syllable quickly and quietly; do not give it a full written vowel.',
    drillWords: ['about', 'support', 'banana', 'pencil', 'today', 'problem'],
    shadowCue: 'Selective shadowing: speak only the stressed words first, then add the reduced words around them.',
    speakingPrompt: 'Give a short project update while deliberately reducing a, to, and, and for.',
    workplace: [
      { phrase: 'The purpose of this meeting is to review the current status.', use: 'Set a meeting objective.' },
      { phrase: 'We are on track for the planned release.', use: 'Give a concise status.' },
      { phrase: 'There are no major risks at the moment.', use: 'Report risk level.' },
    ],
  },
  {
    day: 9,
    week: 'Sound clean-up',
    title: 'Weak forms in real sentences',
    focus: 'Keep function words light so important words stand out.',
    listeningFocus: 'Find five weak forms in the transcript: a, the, to, for, can, was, were, have, or and. Replay each in context.',
    mechanicsTitle: 'Weak forms · grammar words',
    mechanicsCue: 'Say the full form once, then the natural weak form inside the sentence. The meaning word gets the beat.',
    drillWords: ['to → tə', 'and → ən', 'for → fə', 'can → kən', 'was → wəz'],
    shadowCue: 'Shadow one thought group at a time. Tap only the content words and let grammar words fit between taps.',
    speakingPrompt: 'Explain how to reproduce a bug in five steps without stressing every word.',
    workplace: [
      { phrase: 'Here is what we know so far.', use: 'Separate facts from assumptions.' },
      { phrase: 'We can reproduce the issue in the staging environment.', use: 'Report evidence.' },
      { phrase: 'We are still investigating the root cause.', use: 'State what remains unknown.' },
    ],
  },
  {
    day: 10,
    week: 'Sound clean-up',
    title: 'Past-tense endings',
    focus: 'Pronounce -ed as one of three sounds, not one extra syllable every time.',
    listeningFocus: 'Highlight past-tense verbs in the transcript and classify the ending you actually hear.',
    mechanicsTitle: '-ed endings · /t/ /d/ /ɪd/',
    mechanicsCue: 'Use /ɪd/ only after t or d; /t/ after a voiceless sound; /d/ after a voiced sound. Keep one final beat unless /ɪd/.',
    drillWords: ['started / needed', 'worked / washed', 'used / moved', 'fixed / planned'],
    shadowCue: 'Record five transcript sentences containing past verbs. Check that final consonants are audible but not exaggerated.',
    speakingPrompt: 'Report what you completed yesterday using at least six regular past-tense verbs.',
    workplace: [
      { phrase: 'I completed the implementation and updated the documentation.', use: 'Report completed work.' },
      { phrase: 'I also tested the main failure scenarios.', use: 'Add supporting work.' },
      { phrase: 'The change is ready for review.', use: 'Hand work to the next person.' },
    ],
  },
  {
    day: 11,
    week: 'Sound clean-up',
    title: 'Plural and third-person endings',
    focus: 'Make final /s/, /z/, and /ɪz/ audible.',
    listeningFocus: 'Choose a third clip in your accent model. Listen twice and circle every plural or third-person verb in 30 seconds.',
    mechanicsTitle: '-s endings · /s/ /z/ /ɪz/',
    mechanicsCue: 'Use /ɪz/ after sibilant sounds; /s/ after voiceless sounds; /z/ after voiced sounds. Feel throat vibration for /z/.',
    drillWords: ['works / runs', 'tests / builds', 'washes / changes', 'maps / logs'],
    shadowCue: 'Read the transcript slowly, then shadow at 0.75×. Do not drop final consonants when the next word begins.',
    speakingPrompt: 'Describe what your application does using present-simple verbs.',
    workplace: [
      { phrase: 'This service receives requests and validates the input.', use: 'Describe a system component.' },
      { phrase: 'It stores the result and sends a response to the client.', use: 'Explain a flow.' },
      { phrase: 'The monitoring job checks for failures every five minutes.', use: 'Describe operational behaviour.' },
    ],
  },
  {
    day: 12,
    week: 'Sound clean-up',
    title: 'Consonant clusters',
    focus: 'Keep all sounds without adding an extra vowel.',
    listeningFocus: 'Slow the clip to 0.75× and find words ending in two or three consonants. Replay the boundary into the next word.',
    mechanicsTitle: 'Clusters · one beat, several consonants',
    mechanicsCue: 'Build the word from the final sound backward. Tap once per syllable so “tests” never becomes “test-es”.',
    drillWords: ['tests', 'tasks', 'scripts', 'prompts', 'asked', 'worked'],
    shadowCue: 'Shadow only sentences containing clusters. Pause, build the hard word, then restore the whole sentence rhythm.',
    speakingPrompt: 'Explain your daily engineering workflow using tests, tasks, scripts, prompts, and builds.',
    workplace: [
      { phrase: 'I have a few questions about the acceptance criteria.', use: 'Open a requirements discussion.' },
      { phrase: 'Which scenarios should be included in the first release?', use: 'Clarify scope.' },
      { phrase: 'I suggest we document the edge cases before implementation.', use: 'Propose a risk-reducing action.' },
    ],
  },
  {
    day: 13,
    week: 'Sound clean-up',
    title: 'Do not lose final sounds',
    focus: 'Protect meaning carried by final consonants.',
    listeningFocus: 'Dictate ten short phrases and check endings first: tense, plural, and word identity.',
    mechanicsTitle: 'Final contrasts · voiced and voiceless',
    mechanicsCue: 'Hold the vowel steady, then release the final consonant once. Do not add “uh” after it.',
    drillWords: ['back / bag', 'hat / had', 'bus / buzz', 'pick / pig'],
    shadowCue: 'Use a pencil to mark every important final sound in the transcript, then record one clean pass.',
    speakingPrompt: 'Give a concise handover: what changed, what remains, and what the next engineer should check.',
    workplace: [
      { phrase: 'I have pushed the latest changes to the feature branch.', use: 'Start a handover.' },
      { phrase: 'The main path works, but the timeout case still needs testing.', use: 'Separate done from pending.' },
      { phrase: 'Please check the configuration before you run it locally.', use: 'Give a precise next action.' },
    ],
  },
  {
    day: 14,
    week: 'Sound clean-up',
    title: 'Week-two recording audit',
    focus: 'Keep only the sound work that improves understanding.',
    listeningFocus: 'Replay one old recording and today’s clip. List three differences you can hear, not three things you dislike.',
    mechanicsTitle: 'Personal top-three clean-up',
    mechanicsCue: 'Choose one vowel, one consonant, and one ending. Run listen → identify → produce → record → verify.',
    drillWords: ['your weakest vowel pair', 'your weakest consonant pair', 'one -ed set', 'one -s set'],
    shadowCue: 'Perform the seven-step shadowing cycle on 30–45 seconds and save the final pass as Week 2.',
    speakingPrompt: 'Give a 90-second update and check it with phone dictation. Repeat only sentences that transcribe incorrectly.',
    workplace: [
      { phrase: 'The key point is that the issue is isolated to one component.', use: 'Emphasise the main finding.' },
      { phrase: 'As a temporary solution, we can disable the optional feature.', use: 'Offer a workaround.' },
      { phrase: 'I recommend a permanent fix in the next iteration.', use: 'Separate workaround from solution.' },
    ],
  },
  {
    day: 15,
    week: 'Prosody',
    title: 'Word stress changes meaning',
    focus: 'Make one syllable clearly stronger than the others.',
    listeningFocus: 'Mark the strongest syllable in ten content words from the clip. Verify unfamiliar words in Cambridge.',
    mechanicsTitle: 'Word stress · nouns and verbs',
    mechanicsCue: 'Lengthen and slightly raise the stressed vowel; reduce the other syllable. Contrast noun REcord with verb reCORD.',
    drillWords: ['REcord / reCORD', 'PREsent / preSENT', 'CONtract / conTRACT', 'PROgress / proGRESS'],
    shadowCue: 'Shadow only the stressed syllables first, then restore complete words without losing the peaks.',
    speakingPrompt: 'Use each stress-shifting word in one workplace sentence.',
    workplace: [
      { phrase: 'Could you record the decision in the meeting notes?', use: 'Practise reCORD as a verb.' },
      { phrase: 'The deployment record shows the exact time of the failure.', use: 'Practise REcord as a noun.' },
      { phrase: 'I will present our progress at the next review.', use: 'Practise preSENT and PROgress.' },
    ],
  },
  {
    day: 16,
    week: 'Prosody',
    title: 'Numbers that cannot be misunderstood',
    focus: 'Separate -teen from -ty and group long numbers.',
    listeningFocus: 'Search five number pairs in YouGlish or dictionary audio. Listen for final stress in thirteen and first stress in thirty.',
    mechanicsTitle: 'Number stress · 13 vs 30',
    mechanicsCue: 'Stress the second syllable in -teen; stress the first in -ty. Say important numbers once, pause, then repeat them.',
    drillWords: ['thirTEEN / THIRty', 'fourTEEN / FORty', 'fifTEEN / FIFty', 'nineTEEN / NINEty'],
    shadowCue: 'Shadow sentences with dates, percentages, or times. Tap the stressed syllable and keep the final /n/ in -teen.',
    speakingPrompt: 'Say five dates, five percentages, and five times into dictation. Repeat until the transcript is correct.',
    workplace: [
      { phrase: 'The error rate dropped from thirteen percent to three percent.', use: 'Report a metric clearly.' },
      { phrase: 'The meeting starts at three thirty and ends at four fifteen.', use: 'State times without ambiguity.' },
      { phrase: 'We expect thirty users in the first test group.', use: 'State a quantity.' },
    ],
  },
  {
    day: 17,
    week: 'Prosody',
    title: 'Build an English rhythm',
    focus: 'Stress content words and reduce grammar words.',
    listeningFocus: 'Underline nouns, main verbs, adjectives, and adverbs in one transcript paragraph. Listen for their beats.',
    mechanicsTitle: 'Sentence stress · content carries the beat',
    mechanicsCue: 'Clap on meaning words. Fit small function words between claps without slowing the sentence.',
    drillWords: ['I WENT to the STAtion', 'We NEED the FINAL VERsion', 'The TEST failed LAST NIGHT'],
    shadowCue: 'Selective shadowing: say only stressed words with the speaker; on the second pass, add every word.',
    speakingPrompt: 'Explain a simple architecture while stressing only the components and actions that matter.',
    workplace: [
      { phrase: 'We need the final design before we start implementation.', use: 'Make NEED, FINAL DESIGN, START, and IMPLEMENTATION carry the message.' },
      { phrase: 'The client reported a new issue this morning.', use: 'Keep small words reduced.' },
      { phrase: 'Our next priority is improving response time.', use: 'Stress the priority and target.' },
    ],
  },
  {
    day: 18,
    week: 'Prosody',
    title: 'Move the meaning with stress',
    focus: 'Use contrastive stress to correct or emphasise one fact.',
    listeningFocus: 'Replay one sentence several times and decide which word carries the speaker’s correction or contrast.',
    mechanicsTitle: 'Contrastive stress · one sentence, different meanings',
    mechanicsCue: 'Say the same sentence four times. Move the main stress and explain what each version corrects.',
    drillWords: ['I WAS waiting for you', 'I was WAITING for you', 'I was waiting for YOU'],
    shadowCue: 'Copy the speaker’s strongest word and pitch movement. Record before checking the transcript markup.',
    speakingPrompt: 'Correct three imaginary misunderstandings by moving stress to the corrected information.',
    workplace: [
      { phrase: 'I updated the API, not the database.', use: 'Correct the changed component.' },
      { phrase: 'We need the result today, not tomorrow.', use: 'Correct the deadline.' },
      { phrase: 'The problem occurs in production, not in staging.', use: 'Correct the environment.' },
    ],
  },
  {
    day: 19,
    week: 'Prosody',
    title: 'Speak in thought groups',
    focus: 'Pause between ideas rather than after every few words.',
    listeningFocus: 'Add slash marks to one transcript paragraph wherever the speaker completes a small idea. Verify by listening.',
    mechanicsTitle: 'Pausing · one idea per breath group',
    mechanicsCue: 'Read to the slash, pause silently, breathe if needed, then continue. Stress the last key word before each pause.',
    drillWords: ['After the deploy / we checked the logs / and found the cause.', 'If the test passes / we can release today.'],
    shadowCue: 'Shadow full thought groups without stopping inside them. Restart only at the next slash if you fall behind.',
    speakingPrompt: 'Explain a process in four thought groups. Record, mark your pauses, and try once more.',
    workplace: [
      { phrase: 'Before we make a decision, I would like to review the data.', use: 'Pause after the opening condition.' },
      { phrase: 'Based on the current evidence, the change appears safe.', use: 'Pause after the evidence frame.' },
      { phrase: 'If everyone agrees, we can proceed with the release.', use: 'Pause between condition and action.' },
    ],
  },
  {
    day: 20,
    week: 'Prosody',
    title: 'Intonation that guides the listener',
    focus: 'Use falling, rising, and fall-rise movement intentionally.',
    listeningFocus: 'Draw arrows above five transcript lines: fall for statements and wh-questions, rise for yes/no questions, fall-rise for polite uncertainty.',
    mechanicsTitle: 'Pitch movement · ↘ ↗ ↘↗',
    mechanicsCue: 'Exaggerate the arrow first, then reduce it until it sounds natural. Keep the final key word clear.',
    drillWords: ['Where is the log file? ↘', 'Is the service healthy? ↗', 'Could we try another option? ↘↗'],
    shadowCue: 'Hum the melody of three sentences, then speak them with the same pitch path.',
    speakingPrompt: 'Ask two information questions, two yes/no questions, and make two polite suggestions.',
    workplace: [
      { phrase: 'What caused the failure in the first place?', use: 'Use a falling wh-question.' },
      { phrase: 'Have we tested the rollback procedure?', use: 'Use a rising yes/no question.' },
      { phrase: 'Could we review one more option before we decide?', use: 'Use a polite fall-rise.' },
    ],
  },
  {
    day: 21,
    week: 'Prosody',
    title: 'Week-three prosody audit',
    focus: 'Make stress and pauses do more work than individual sounds.',
    listeningFocus: 'Listen to 45 seconds and mark word stress, sentence beats, thought groups, and final pitch before reading aloud.',
    mechanicsTitle: 'Prosody score · stress, rhythm, pause, pitch',
    mechanicsCue: 'Run four passes, one feature at a time. Never try to correct all four in a single pass.',
    drillWords: ['word stress', 'content beats', 'thought-group slashes', 'intonation arrows'],
    shadowCue: 'Complete one seven-step shadowing cycle and save the final pass as Week 3.',
    speakingPrompt: 'Give a two-minute status update with a clear opening, three thought groups, and a firm close.',
    workplace: [
      { phrase: 'There are three points I would like to cover today.', use: 'Preview a structured update.' },
      { phrase: 'First, the implementation is complete; second, testing is in progress.', use: 'Sequence information.' },
      { phrase: 'Finally, I need a decision on the release date.', use: 'Close with the required action.' },
    ],
  },
  {
    day: 22,
    week: 'Real flow',
    title: 'Link across word boundaries',
    focus: 'Connect a final consonant to the next vowel.',
    listeningFocus: 'Mark consonant-to-vowel links in one paragraph and replay each boundary: get_it, turn_on, send_it.',
    mechanicsTitle: 'Linking · consonant + vowel',
    mechanicsCue: 'Keep the final consonant, but let it begin the next syllable. Do not insert a pause between linked words.',
    drillWords: ['get_it', 'turn_it_on', 'send_an_update', 'not_at_all'],
    shadowCue: 'Choose a fresh five-day clip. Shadow only linked phrases, then restore the complete sentence.',
    speakingPrompt: 'Describe how to start an application, open a file, and check an endpoint using linked speech.',
    workplace: [
      { phrase: 'Could you send an update when the test is complete?', use: 'Link send_an and test_is.' },
      { phrase: 'I will look at it and get back to you.', use: 'Link look_at_it and get_back.' },
      { phrase: 'Let us review it after the stand-up.', use: 'Keep the phrase connected but professional.' },
    ],
  },
  {
    day: 23,
    week: 'Real flow',
    title: 'Smooth vowel-to-vowel links',
    focus: 'Use a light /w/ or /j/ glide where speech naturally joins.',
    listeningFocus: 'Listen for tiny glides between two vowels. Confirm with repeated playback rather than forcing every possible glide.',
    mechanicsTitle: 'Glides · /w/ and /j/',
    mechanicsCue: 'Round into /w/ after an oo-like vowel; glide through /j/ after an ee-like vowel. Keep both subtle.',
    drillWords: ['go[w]out', 'do[w]it', 'I[j]agree', 'we[j]asked'],
    shadowCue: 'Shadow the same clip at 0.9×. Focus on smooth boundaries, not faster words.',
    speakingPrompt: 'Give a short opinion using “I agree,” “I also think,” and “we ought to.”',
    workplace: [
      { phrase: 'I agree with the overall direction.', use: 'State agreement clearly.' },
      { phrase: 'I also think we should reduce the initial scope.', use: 'Add one condition to agreement.' },
      { phrase: 'We ought to validate the assumption with users.', use: 'Recommend evidence.' },
    ],
  },
  {
    day: 24,
    week: 'Real flow',
    title: 'Hear safe elision',
    focus: 'Recognise sounds that disappear in fast speech without copying carelessness.',
    listeningFocus: 'Compare transcript and audio. Circle written consonants you cannot hear in clusters such as next day or must be.',
    mechanicsTitle: 'Elision · simplify difficult clusters',
    mechanicsCue: 'Say the careful form first. Then remove only the sound the model speaker removes while keeping the words intelligible.',
    drillWords: ['next day → nex day', 'must be → mus be', 'sandwich → sanwich', 'tell him → tellim'],
    shadowCue: 'Shadow the speaker’s actual reduced form, then record a careful and a conversational version.',
    speakingPrompt: 'Explain yesterday’s work twice: once careful, once conversational. Keep both understandable.',
    workplace: [
      { phrase: 'The next step is to test the rollback.', use: 'Keep “next step” compact but clear.' },
      { phrase: 'This must be reviewed before release.', use: 'Practise the cluster without an extra vowel.' },
      { phrase: 'I asked him to update the ticket.', use: 'Link asked_him without losing meaning.' },
    ],
  },
  {
    day: 25,
    week: 'Real flow',
    title: 'Assimilation: sounds influence neighbours',
    focus: 'Recognise natural changes such as ten boys → tem boys.',
    listeningFocus: 'Replay phrase boundaries and identify where mouth position anticipates the next sound.',
    mechanicsTitle: 'Assimilation · prepare the next sound',
    mechanicsCue: 'Copy only common, audible changes. The goal is easier flow and better listening, not slang performance.',
    drillWords: ['ten boys → tem boys', 'handbag → hambag', 'did you → didja', 'got you → gotcha'],
    shadowCue: 'Use full-speed overlap for 20–30 seconds. Recover at the next thought-group boundary if you fall behind.',
    speakingPrompt: 'Ask and answer five short workplace questions with natural “did you” and “could you” links.',
    workplace: [
      { phrase: 'Did you have a chance to review the change?', use: 'Use natural connected “did you” without becoming unclear.' },
      { phrase: 'Could you share your feedback by the end of the day?', use: 'Make a polite request.' },
      { phrase: 'I will get you the details after lunch.', use: 'Link get_you lightly.' },
    ],
  },
  {
    day: 26,
    week: 'Real flow',
    title: 'Informal reductions with judgement',
    focus: 'Understand gonna and wanna; choose careful forms in formal settings.',
    listeningFocus: 'Choose the final five-day clip. Note reductions in casual speech and label each safe for formal, neutral, or casual contexts.',
    mechanicsTitle: 'Register · going to, want to, have to',
    mechanicsCue: 'Practise both forms. Use the complete form in presentations and careful updates; recognise reductions in conversation.',
    drillWords: ['going to / gonna', 'want to / wanna', 'have to / hafta', 'give me / gimme'],
    shadowCue: 'Shadow a conversational section first as spoken, then deliver the same meaning in neutral workplace speech.',
    speakingPrompt: 'Explain your plan for tomorrow in a casual version and a meeting-ready version.',
    workplace: [
      { phrase: 'I am going to investigate the logs first.', use: 'Use the full form in a formal update.' },
      { phrase: 'I want to confirm the expected behaviour.', use: 'Use neutral professional speech.' },
      { phrase: 'I have to verify one dependency before I commit to a date.', use: 'State a necessary condition.' },
    ],
  },
  {
    day: 27,
    week: 'Real flow',
    title: 'Full-speed news shadowing',
    focus: 'Stay with the speaker and recover instead of stopping.',
    listeningFocus: 'Listen twice at normal speed without text. Write the topic, three facts, and one phrase you missed.',
    mechanicsTitle: 'Recovery · rejoin at the next stressed word',
    mechanicsCue: 'Practise falling behind on purpose, then jump back in at the next content word or pause. Never restart the recording.',
    drillWords: ['miss → listen → rejoin', 'stress anchor', 'pause anchor', 'meaning over perfection'],
    shadowCue: 'Do three uninterrupted passes: with text, without text, then overlap. Record only the last pass.',
    speakingPrompt: 'Summarise the clip in 90 seconds without reading your transcript.',
    workplace: [
      { phrase: 'My understanding is that the change affects only new requests.', use: 'State your current interpretation.' },
      { phrase: 'The existing data should remain unchanged.', use: 'State an expected boundary.' },
      { phrase: 'I will verify that assumption before the release.', use: 'Commit to checking uncertainty.' },
    ],
  },
  {
    day: 28,
    week: 'Real flow',
    title: 'Two minutes without a script',
    focus: 'Organise ideas fast enough to keep speaking.',
    listeningFocus: 'Listen to your clip once and retell it immediately. Check the transcript only after the retell.',
    mechanicsTitle: 'Fluency frame · past, present, next',
    mechanicsCue: 'Use three anchors: what happened, what it means now, what happens next. Pause between anchors instead of filling with “uh”.',
    drillWords: ['What happened?', 'What does it mean?', 'What happens next?', 'What do I need?'],
    shadowCue: 'Shadow one final pass, then close the source and speak on the same topic for two minutes.',
    speakingPrompt: 'Talk for two minutes: one thing you did, one thing you learned, and one thing you will do.',
    workplace: [
      { phrase: 'Yesterday I finished the main implementation.', use: 'Anchor the past.' },
      { phrase: 'Today I am validating the edge cases.', use: 'Anchor the present.' },
      { phrase: 'Next, I will prepare the change for review.', use: 'Anchor the next action.' },
    ],
  },
  {
    day: 29,
    week: 'Integration',
    title: 'Simulated meeting',
    focus: 'Combine clear pronunciation with useful workplace moves.',
    listeningFocus: 'Watch one minute of a meeting or interview. Write down how the speaker enters, clarifies, disagrees, and closes.',
    mechanicsTitle: 'Meeting control · pace and turn-taking',
    mechanicsCue: 'Pause before your key point, stress the action, and finish the sentence. Do not speed up to avoid interruption.',
    drillWords: ['enter the discussion', 'clarify', 'disagree politely', 'summarise', 'assign an action'],
    shadowCue: 'Shadow five useful meeting lines, then replace their content with your own project details.',
    speakingPrompt: 'Run a five-minute solo meeting: opening, update, blocker, recommendation, questions, and summary.',
    workplace: [
      { phrase: 'May I add one point before we move on?', use: 'Enter the discussion politely.' },
      { phrase: 'I understand the concern; however, the data suggests a different conclusion.', use: 'Disagree with evidence.' },
      { phrase: 'Let us confirm the owner and deadline for each action item.', use: 'Close with accountability.' },
    ],
  },
  {
    day: 30,
    week: 'Integration',
    title: 'Final clarity check and next cycle',
    focus: 'Compare Day 1 with Day 30 and choose the next three targets.',
    listeningFocus: 'Use the Day 1 clip again. Dictate the same section and compare the number and type of misses.',
    mechanicsTitle: 'Personal scorecard · evidence over accent',
    mechanicsCue: 'Score first-listen understanding, pauses, word stress, sentence stress, endings, and ASR accuracy. Keep the three weakest items.',
    drillWords: ['first-listen clarity', 'stress', 'rhythm', 'endings', 'ASR accuracy'],
    shadowCue: 'Repeat the Day 1 shadow section at normal speed. Save it beside the baseline and compare only observable differences.',
    speakingPrompt: 'Record a final two-minute introduction and project update. Create the next 30-day plan from your three remaining blockers.',
    workplace: [
      { phrase: 'Over the past month, I have made consistent progress in spoken clarity.', use: 'Describe development without exaggeration.' },
      { phrase: 'My next focus will be smoother delivery in technical discussions.', use: 'Name the next growth target.' },
      { phrase: 'I would appreciate specific feedback on my pace and sentence stress.', use: 'Ask for actionable feedback.' },
    ],
  },
]
